name: Run tests on staging
on:
  push:
    branches:
      - main
      - NDEV-21411
  workflow_dispatch:

jobs:
  fetch-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App token for go-nctl repository
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.NCTL_VERSION_BUMPER_GITHUB_APP_ID }}
          private-key: ${{ secrets.NCTL_VERSION_BUMPER_GITHUB_APP_PVT_KEY }}
          owner: nirmata
          repository: go-nctl
          
      - name: Fetch latest go-nctl release
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          npm install axios
          node -e "
          const axios = require('axios');
          axios.get('https://api.github.com/repos/nirmata/go-nctl/releases', {
            headers: {
              Authorization: \`token \${process.env.TOKEN}\`,
              Accept: 'application/vnd.github+json'
            }
          }).then(response => {
            const releases = response.data;
            if (releases.length > 0) {
              console.log('Latest release:', releases[0]);
            } else {
              console.log('No releases found.');
            }
          }).catch(err => {
            console.error('Error fetching releases:', err.response?.data || err);
          });
          "
